CREATE ROLE worker_role WITH CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE CarOperation TO worker_role;

CREATE ROLE worker_role WITH CREATEROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO worker_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO worker_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO worker_role;

CREATE USER user_worker WITH PASSWORD 'zx3021';
GRANT worker_role TO user_worker;

CREATE USER user_watcher WITH PASSWORD '123';
GRANT watcher_role TO user_watcher;